//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessRulesEngine.SharedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Orders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Orders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessRulesEngine.SharedResources.Orders", typeof(Orders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;BOOK_ORDER&quot;,    
        ///  &quot;productId&quot;:&quot;BOOK001&quot;,
        ///  &quot;productType&quot;: &quot;Physical&quot;,
        ///  &quot;productSubType&quot;: &quot;Book&quot;,
        ///  &quot;productName&quot;: &quot;The Day of The Triffids&quot;,  
        ///  &quot;agentId&quot; : &quot;BOOK_AGENT_ID&quot;  
        ///}.
        /// </summary>
        public static string Book_json {
            get {
                return ResourceManager.GetString("Book_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;MEMBERSHIP_ACTIVATION_ORDER&quot;,    
        ///  &quot;productId&quot;: &quot;ACTIVATION_MEMBER_ID&quot;,
        ///  &quot;productType&quot;: &quot;Membership&quot;,
        ///  &quot;productSubType&quot;: &quot;Activate&quot;,
        ///  &quot;productName&quot;: &quot;Membership Activation&quot;,  
        ///  &quot;agentId&quot; : &quot;MEMBERSHIP_ACTIVATION_AGENT_ID&quot;  
        ///}.
        /// </summary>
        public static string Membership_Activation_json {
            get {
                return ResourceManager.GetString("Membership_Activation_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;MEMBERSHIP_UPGRADE_ORDER&quot;,    
        ///  &quot;productId&quot;: &quot;UPGRADE_MEMBER_ID&quot;,
        ///  &quot;productType&quot;: &quot;Membership&quot;,
        ///  &quot;productSubType&quot;: &quot;Upgrade&quot;,
        ///  &quot;productName&quot;: &quot;Membership Upgrade&quot;,  
        ///  &quot;agentId&quot; : &quot;MEMBERSHIP_UPGRADE_AGENT_ID&quot;  
        ///}.
        /// </summary>
        public static string Membership_Upgrade_json {
            get {
                return ResourceManager.GetString("Membership_Upgrade_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;PHYSICAL_PRODUCT_ORDER&quot;,  
        ///  &quot;productId&quot;:&quot;CAKE001&quot;,
        ///  &quot;productType&quot;: &quot;Physical&quot;,
        ///  &quot;productSubType&quot;: &quot;Cake&quot;,
        ///  &quot;productName&quot;: &quot;Battenberg&quot;,  
        ///  &quot;agentId&quot; : &quot;PHYSICAL_PRODUCT_AGENT_ID&quot;
        ///}.
        /// </summary>
        public static string Physical_Product_json {
            get {
                return ResourceManager.GetString("Physical_Product_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;VIDEO_ORDER&quot;,    
        ///  &quot;productId&quot;:&quot;VIDEO001&quot;,
        ///  &quot;productType&quot;: &quot;Physical&quot;,
        ///  &quot;productSubType&quot;: &quot;Video&quot;,
        ///  &quot;productName&quot;: &quot;Learning to Ski&quot;,  
        ///  &quot;agentId&quot; : &quot;VIDEO_AGENT_ID&quot;  
        ///}.
        /// </summary>
        public static string Video_json {
            get {
                return ResourceManager.GetString("Video_json", resourceCulture);
            }
        }
    }
}
